name: Deploy

on:
    repository_dispatch:
        types: [dispatch-deploy]
    push:
        branches:
            - main

jobs:
    update_readme:
        if: github.event_name == 'repository_dispatch'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Update
              env:
                  VERSION: ${{ github.event.client_payload.version }}
              run: |
                  NOW=$(date '+%Y-%m-%d %H:%M:%S %Z')
                  sed -i "s/API 版本: .*/API 版本: v${{ env.VERSION }}/" README.md
                  sed -i "s|生成时间: .*|生成时间: ${NOW}|" README.md
            - name: Commit
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add README.md
                  git commit -m "chore: update README"
                  git push

    deploy:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/checkout@v4
              with:
                  repository: AuTsing/denofa_core
                  path: api/denofa_core
                  token: ${{ secrets.DENOFA_CORE_TOKEN }}

            - uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Build
              run: |
                  cp api/denofa_core/src/dts/*.d.ts api/
                  npm install --frozen-lockfile
                  npm run predocs
                  npm run docs:build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/.vitepress/dist
                  cname: denofa.qzz.io
