name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/checkout@v4
              with:
                  repository: AuTsing/denofa_core
                  path: api/denofa_core
                  token: ${{ secrets.DENOFA_CORE_TOKEN }}

            - uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Build
              run: |
                  cp api/denofa_core/src/dts/*.d.ts api/
                  npm install --frozen-lockfile
                  npm run predocs
                  npm run docs:build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/.vitepress/dist
                  cname: denofa.qzz.io
